config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'about', to: 'home#about'
  get 'feedback', to: 'home#feedback'
  get 'network', to: 'home#network'
  get 'contact', to: 'home#contact'

  scope "/:locale" do 
    get '/', to: 'home#index'
    get 'about', to: 'home#about'
    get 'feedback', to: 'home#feedback'
    get 'network', to: 'home#network'
    get 'contact', to: 'home#contact' 
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
    
    if I18n.locale == :zh
      @tab_locale = :en
    elsif I18n.locale == :en
      @tab_locale = :zh
    end
  end

  def default_url_options(options={})
    logger.debug "default_url_options is passed options: #{options.inspect}\n"
    { locale: I18n.locale }
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def feedback
  end

  def network
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_product_list.html.erb
<td width="201" height="225" valign="top">
  <table width="187" border="0" cellspacing="0" cellpadding="0">
  <tbody>
  <tr>
    <td>
      <img src="<%= image_url('plist.jpg') %>" width="187">
    </td>
  </tr>
  <tr>
    <td background="<%= image_url('plistbg.gif') %>">
      <table width="170" align="center" cellpadding="0" cellspacing="0">
      <script language="javascript1.2">
        function showsubmenub(sid)
        {
          whichEl = eval("submenub" + sid);
          if (whichEl.style.display == "none")
          {
            eval("submenub" + sid + ".style.display=\"\";");
          }
          else
          {
            eval("submenub" + sid + ".style.display=\"none\";");
          }
        }
      </script>
      <script language="javascript1.2">
        function showsubmenu(sid)
        {
          whichEl = eval("submenu" + sid);
          if (whichEl.style.display == "none")
          {
            var countt
            eval("submenu" + sid + ".style.display=\"\";");
          }
          else
          {
            eval("submenu" + sid + ".style.display=\"none\";");
          }
        }
      </script>
      <tbody>
      </table>
    </td>
  </tr>
  <tr>
    <td>
      <img src="<%= image_url('plistbtm.jpg') %>" width="187" height="36">
    </td>
  </tr>
  </tbody>
  </table>
</td>

app/views/home/about.en.html.erb
<table width="970" border="0" align="center" cellpadding="0" cellspacing="0">
  <tbody>
    <tr>
      <%= render :partial => 'product_list' %>
      <td width="769" valign="top" style="padding-top:14px;"><table width="768" border="0" align="right" cellpadding="0" cellspacing="0">
      <tbody><tr>
        <td height="35" background="<%= image_url('barbg.jpg') %>"><table width="744" border="0" align="center" cellpadding="0" cellspacing="0">
          <tbody><tr>
            <td width="206"><span class="STYLE2">About us</span></td>
            <td width="538" align="right">You are here:Home&gt;&gt;About us</td>
          </tr>
        </tbody></table></td>
      </tr>
      <tr>
        <td height="25">&nbsp;</td>
      </tr>
      <tr>
        <td><table width="720" border="0" align="center" cellpadding="0" cellspacing="0">
          <tbody><tr>
            <td> 
<p>Hangzhou RiPei Trading Co., Ltd is a set of Home Furnishing daily development, production and sales as one of the Professional Company.Focus on createing their own high-quality daily-use products for Chinese. Has been adhering to the low profile of high standard international top brands and Chinese Internet brand, employ the national best daily class industrial designers in product design, let more families can spend less cost to buy the same products as international top brands. The company always uphold the integrity-based business philosophy, fulfil the commitments to customers, and sincerely look forward to working with people from all walks of life at home and abroad and seek common development, create the future.</p></td>
            </tr>
        </tbody></table></td>
      </tr>
    </tbody></table></td>
    </tr>
  </tbody>
</table>

app/views/home/about.html.erb
<table width="970" border="0" align="center" cellpadding="0" cellspacing="0">
  <tbody>
    <tr>
      <%= render :partial => 'product_list' %>
      <td width="769" valign="top" style="padding-top:14px;">
        <table width="768" border="0" align="right" cellpadding="0" cellspacing="0">
        <tbody>
        <tr>
          <td height="35" background="<%= image_url('barbg.jpg') %>">
            <table width="744" border="0" align="center" cellpadding="0" cellspacing="0">
            <tbody>
            <tr>
              <td width="206">
                <span class="STYLE2">公司简介</span>
              </td>
              <td width="538" align="right">
                您当前所在位置：首页&gt;&gt;公司简介
              </td>
            </tr>
            </tbody>
            </table>
          </td>
        </tr>
        <tr>
          <td height="25">
            &nbsp;
          </td>
        </tr>
        <tr>
          <td>
            <table width="720" border="0" align="center" cellpadding="0" cellspacing="0">
            <tbody>
            <tr>
              <td>
                <p>
                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                </p>
                <p>
                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <font style="FONT-SIZE: 14pt; FONT-FAMILY: 楷体_GB2312">武义县盛宏餐具制品厂</font><font style="FONT-SIZE: 12pt; FONT-FAMILY: 楷体_GB2312">是一家专业生产密胺餐具的厂家，密胺餐具也称美耐皿餐具，是一种国际流行的新型餐具。该产品品质优良，制作精细，具有无毒，无味，耐酸、碱、高强度，便于洗涤等特点，可按客户的需求定制，产品远销中东，欧洲，美国等国家和地区。</font>
                </p>
                <p>
                  <font face="楷体_GB2312" size="3">&nbsp;&nbsp;&nbsp; </font><font style="FONT-SIZE: 12pt; FONT-FAMILY: 楷体_GB2312">公司始终坚持诚信的经营理念，旅行对客户的承诺，并精诚期待与海内外各界人士共谋发展、共创未来......<br style="FONT-FAMILY: ">
                  </font>
                </p>
              </td>
            </tr>
            </tbody>
            </table>
          </td>
        </tr>
        </tbody>
        </table>
      </td>
    </tr>
  </tbody>
</table>

app/views/home/about.zh.html.erb
<table width="970" border="0" align="center" cellpadding="0" cellspacing="0">
  <tbody>
    <tr>
      <%= render :partial => 'product_list' %>
      <td width="769" valign="top" style="padding-top:14px;">
        <table width="768" border="0" align="right" cellpadding="0" cellspacing="0">
        <tbody>
        <tr>
          <td height="35" background="<%= image_url('barbg.jpg') %>">
            <table width="744" border="0" align="center" cellpadding="0" cellspacing="0">
            <tbody>
            <tr>
              <td width="206">
                <span class="STYLE2">公司简介</span>
              </td>
              <td width="538" align="right">
                您当前所在位置：首页&gt;&gt;公司简介
              </td>
            </tr>
            </tbody>
            </table>
          </td>
        </tr>
        <tr>
          <td height="25">
            &nbsp;
          </td>
        </tr>
        <tr>
          <td>
            <table width="720" border="0" align="center" cellpadding="0" cellspacing="0">
            <tbody>
            <tr>
              <td>
                <p>
                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                </p>
                <p>
                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <font style="FONT-SIZE: 14pt; FONT-FAMILY: 楷体_GB2312">杭州日沛贸易有限公司</font><font style="FONT-SIZE: 12pt; FONT-FAMILY: 楷体_GB2312">是一家集家居日用开发、生产和销售为一体的专业公司。
</font>
                </p>
                <p>
                  <font face="楷体_GB2312" size="3">&nbsp;&nbsp;&nbsp; </font><font style="FONT-SIZE: 12pt; FONT-FAMILY: 楷体_GB2312">日沛RPPZ风靡欧美市场的时尚轻奢家居品牌，凭借高档品质，平实的价格，健康的理念，融入自己个性化的设计，并采用德国先进制造工艺，让“日沛RPPZ”一经推出，就迅速得到广大客户的认可。我们以中国互联网低姿态，坚持诚信为本的经营理念，精诚期待与海内外各界人士共谋发展共创未来。<br style="FONT-FAMILY: ">
                  </font>
                </p>
              </td>
            </tr>
            </tbody>
            </table>
          </td>
        </tr>
        </tbody>
        </table>
      </td>
    </tr>
  </tbody>
</table>

app/views/home/contact.en.html.erb
<table width="970" border="0" align="center" cellpadding="0" cellspacing="0">
  <tbody>
    <tr>
      <%= render :partial => 'product_list' %>
      <td width="769" valign="top" style="padding-top:14px;"><table width="768" border="0" align="right" cellpadding="0" cellspacing="0">
      <tbody><tr>
        <td height="35" background="<%= image_url('barbg.jpg') %>"><table width="744" border="0" align="center" cellpadding="0" cellspacing="0">
          <tbody><tr>
            <td width="206"><span class="STYLE2">Contact us</span></td>
            <td width="538" align="right">You are here:Home&gt;&gt;Contact us</td>
          </tr>
        </tbody></table></td>
      </tr>
      <tr>
        <td height="25">&nbsp;</td>
      </tr>
      <tr>
        <td><table width="720" border="0" align="center" cellpadding="0" cellspacing="0">
          <tbody><tr>
            <td></td>
            </tr>
        </tbody></table></td>
      </tr>
    </tbody></table></td>
    </tr>
  </tbody>
</table>

app/views/home/contact.html.erb
<table width="970" border="0" align="center" cellpadding="0" cellspacing="0">
  <tbody>
    <tr>
      <%= render :partial => 'product_list' %>
      <td width="769" valign="top" style="padding-top:14px;"><table width="768" border="0" align="right" cellpadding="0" cellspacing="0">
      <tbody><tr>
        <td height="35" background="<%= image_url('barbg.jpg') %>"><table width="744" border="0" align="center" cellpadding="0" cellspacing="0">
          <tbody><tr>
            <td width="206"><span class="STYLE2">联系我们</span></td>
            <td width="538" align="right">您当前所在位置：首页&gt;&gt;联系我们</td>
          </tr>
        </tbody></table></td>
      </tr>
      <tr>
        <td height="25">&nbsp;</td>
      </tr>
      <tr>
        <td><table width="720" border="0" align="center" cellpadding="0" cellspacing="0">
          <tbody><tr>
            <td><p><font style="FONT-SIZE: 14pt">武义县盛宏餐具制品厂</font></p>
<p>地址：中国.浙江.武义东南工业园区冷水坑</p>
<p>电话:0089-579-7707686</p>
<p>手机:0089-13065950666 13777537535</p>
<p>传真:0089-579-87707685</p>
<p>Email：<a target="_blank" href="mailto:sun030221@hotmail.com">sun030221@hotmail.com</a> <a target="_blank" href="mailto:samsun@shtableware.com">samsun@shtableware.com</a></p>
<p>网址：<a href="http://www.shtableware.com">www.shtableware.com</a></p>
<p>阿里巴巴：<a href="http://ykshxs.cn.alibaba.com">http://ykshxs.cn.alibaba.com</a></p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="http://shtableware.en.alibaba.com">http://shtableware.en.alibaba.com</a></p>
<p>&nbsp;</p></td>
            </tr>
        </tbody></table></td>
      </tr>
    </tbody></table></td>
    </tr>
  </tbody>
</table>

app/views/home/contact.zh.html.erb
<table width="970" border="0" align="center" cellpadding="0" cellspacing="0">
  <tbody>
    <tr>
      <%= render :partial => 'product_list' %>
      <td width="769" valign="top" style="padding-top:14px;"><table width="768" border="0" align="right" cellpadding="0" cellspacing="0">
      <tbody><tr>
        <td height="35" background="<%= image_url('barbg.jpg') %>"><table width="744" border="0" align="center" cellpadding="0" cellspacing="0">
          <tbody><tr>
            <td width="206"><span class="STYLE2">联系我们</span></td>
            <td width="538" align="right">您当前所在位置：首页&gt;&gt;联系我们</td>
          </tr>
        </tbody></table></td>
      </tr>
      <tr>
        <td height="25">&nbsp;</td>
      </tr>
      <tr>
        <td><table width="720" border="0" align="center" cellpadding="0" cellspacing="0">
          <tbody><tr>
            <td></td>
            </tr>
        </tbody></table></td>
      </tr>
    </tbody></table></td>
    </tr>
  </tbody>
</table>

app/views/home/feedback.en.html.erb
<table width="970" border="0" align="center" cellpadding="0" cellspacing="0">
  <tbody>
    <tr>
      <%= render :partial => 'product_list' %>
      <td width="769" valign="top" style="padding-top:14px;"><table width="768" border="0" align="right" cellpadding="0" cellspacing="0">
      <tbody><tr>
        <td height="35" background="<%= image_url('barbg.jpg') %>"><table width="744" border="0" align="center" cellpadding="0" cellspacing="0">
          <tbody><tr>
            <td width="206"><span class="STYLE2">Feedback</span></td>
            <td width="538" align="right">You are here:Home&gt;&gt;Feedback</td>
          </tr>
        </tbody></table></td>
      </tr>
      <tr>
        <td height="25">&nbsp;</td>
      </tr>
      <tr>
        <td><table width="720" border="0" align="center" cellpadding="0" cellspacing="0">
          <tbody><tr>
            <td><table width="460" border="0" align="center" cellpadding="0" cellspacing="0">

                  <form name="form1" method="post" action="?act=add"></form>
                    <tbody><tr>
                      <td height="30" colspan="4" class="rm">Dear Sir/Madam , Welcome to our website ! Please feel free to send your enquiry   to us by the following form,We will contact you as soon as possible and offer   you the corresponding services. </td>
                    </tr>
                    <tr>
                      <td width="63" height="30" class="rm">&nbsp;&nbsp;Subject </td>
                      <td colspan="3"><input name="title" type="text" size="30">
                          <font color="#FF0000">*</font></td>
                    </tr>
                    
                    <tr>
                      <td height="30" class="rm">&nbsp;&nbsp;Name</td>
                      <td height="25" colspan="3"><input name="name" type="text" size="30">
                          <font color="#FF0000">*</font>
                          <input name="sex" type="radio" value="先生" checked="checked">
                        Man
                        <input type="radio" name="sex" value="女士">
                        Lady</td>
                    </tr>
                   
                    <tr>
                      <td height="30">&nbsp;&nbsp;Company</td>
                      <td height="25" colspan="3"><input name="company" type="text" size="30"></td>
                    </tr>
                    
                    <tr>
                      <td height="30" class="rm">&nbsp;&nbsp;Add</td>
                      <td height="25" colspan="3"><input name="add" type="text" size="30"></td>
                    </tr>
                    
                    <tr>
                      <td height="30" class="rm">&nbsp;&nbsp;Tel</td>
                      <td width="173" height="25"><input name="tel" type="text" size="20">
                          <font color="#FF0000"> *</font></td>
                      <td width="63">&nbsp;&nbsp;Fax</td>
                      <td width="156"><input name="fax" type="text" size="20"></td>
                    </tr>
                   
                    <tr>
                      <td height="30" class="rm">&nbsp;&nbsp;http://</td>
                      <td height="25" colspan="3"><input name="homeurl" type="text" size="30"></td>
                    </tr>
                   
                    <tr>
                      <td height="30" class="rm">&nbsp;&nbsp;E-mail</td>
                      <td height="25" colspan="3"><input name="email" type="text" size="30"></td>
                    </tr>
                   
                    <tr align="center">
                      <td height="30" colspan="4" class="rm"><input type="radio" name="type1" value="咨询" checked="checked">
                        Consultation
                          <input name="type1" type="radio" value="定购">
                        Order
                        <input type="radio" name="type1" value="建议">
                        Recommend</td>
                    </tr>
                    <tr>
                      <td height="25" colspan="4"><table width="458" border="0" cellspacing="0" cellpadding="0">
                          <tbody><tr>
                            <td width="55" align="center" class="b12">Content</td>
                            <td width="328" bgcolor="#F6F6F6"><textarea name="content" cols="45" rows="6"></textarea></td>
                            <td width="75">&nbsp;<font color="#FF0000">*</font></td>
                          </tr>
                          <tr>
                            <td height="40" colspan="3" align="center" class="style3"><table width="300" border="0" cellspacing="0" cellpadding="0">
                                <tbody><tr>
                                  <td align="center"><input type="submit" name="Submit3" value="Submit"></td>
                                  <td><input type="reset" name="Submit22" value="Reset"></td>
                                </tr>
                            </tbody></table></td>
                          </tr>
                      </tbody></table></td>
                    </tr>
                  
                </tbody></table>
</td>
            </tr>
        </tbody></table></td>
      </tr>
    </tbody></table></td>
    </tr>
  </tbody>
</table>

app/views/home/feedback.html.erb
<table width="970" border="0" align="center" cellpadding="0" cellspacing="0">
  <tbody>
    <tr>
      <%= render :partial => 'product_list' %>
      <td width="769" valign="top" style="padding-top:14px;"><table width="768" border="0" align="right" cellpadding="0" cellspacing="0">
      <tbody><tr>
        <td height="35" background="<%= image_url('barbg.jpg') %>"><table width="744" border="0" align="center" cellpadding="0" cellspacing="0">
          <tbody><tr>
            <td width="206"><span class="STYLE2">信息反馈</span></td>
            <td width="538" align="right">您当前所在位置：首页&gt;&gt;信息反馈</td>
          </tr>
        </tbody></table></td>
      </tr>
      <tr>
        <td height="25">&nbsp;</td>
      </tr>
      <tr>
        <td><table width="720" border="0" align="center" cellpadding="0" cellspacing="0">
          <tbody><tr>
            <td><table width="527" border="0" align="center" cellpadding="0" cellspacing="0">
    
        <form name="form1" method="post" action="?act=add"></form>
          <tbody><tr>
            <td colspan="4" align="center"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tbody><tr>
                  <td height="40" align="center" class="b12">感谢您对我们网站的访问，如果您对我们的产品感兴趣，我们欢迎您的咨询及订购！</td>
                </tr>
            </tbody></table></td>
          </tr>
          <tr>
            <td width="63" height="30" align="left">&nbsp;&nbsp;标题 </td>
            <td colspan="3"><input name="title" type="text" id="title" size="30">
                <font color="#FF0000">*</font></td>
          </tr>
          
          <tr>
            <td height="30" align="left">&nbsp;&nbsp;联系人</td>
            <td height="25" colspan="3"><input name="name" type="text" size="30">
                <font color="#FF0000">*</font>
                <input name="sex" type="radio" value="先生" checked="">
                先生
                <input type="radio" name="sex" value="女士">
              女士</td>
          </tr>
          
          <tr>
            <td height="30" align="left">&nbsp;&nbsp;公 司</td>
            <td height="25" colspan="3"><input name="company" type="text" size="30"></td>
          </tr>
          
          <tr>
            <td height="30" align="left">&nbsp;&nbsp;地 址</td>
            <td height="25" colspan="3"><input name="add" type="text" size="30"></td>
          </tr>
          
          <tr>
            <td height="30" align="left">&nbsp;&nbsp;电 话</td>
            <td width="210" height="25"><input name="tel" type="text" size="20">
            <font color="#FF0000"> *</font></td>
            <td width="73">&nbsp;&nbsp;传&nbsp;真</td>
            <td width="181"><input name="fax" type="text" size="20"></td>
          </tr>
          
          <tr>
            <td height="30" align="left">&nbsp;&nbsp;http://</td>
            <td height="25" colspan="3"><input name="homeurl" type="text" size="30"></td>
          </tr>
          
          <tr>
            <td height="30" align="left">&nbsp;&nbsp;E-mail</td>
            <td height="25" colspan="3"><input name="email" type="text" size="30"></td>
          </tr>
          
          <tr align="center">
            <td height="30" colspan="4"><div align="center">
              <input type="radio" name="type1" value="咨询" checked="">
                咨询
                <input name="type1" type="radio" value="定购">
                定购
                <input type="radio" name="type1" value="建议">
                建议</div></td>
          </tr>
          <tr>
            <td height="25" colspan="4"><table width="458" border="0" cellspacing="0" cellpadding="0">
                <tbody><tr>
                  <td width="55" align="center" class="b12">留<br>
                    言</td>
                  <td width="328" bgcolor="#F6F6F6"><textarea name="content" cols="45" rows="6"></textarea></td>
                  <td width="75">&nbsp;<font color="#FF0000">*</font></td>
                </tr>
                <tr>
                  <td colspan="3" align="center"><table width="300" border="0" align="center" cellpadding="0" cellspacing="0">
                      <tbody><tr>
                        <td height="40" align="center"><div align="center">
                          <input type="submit" name="Submit3" value="留言">
                        </div></td>
                        <td><div align="center">
                          <input type="reset" name="Submit22" value="撤销">
                        </div></td>
                      </tr>
                  </tbody></table></td>
                </tr>
            </tbody></table></td>
          </tr>
        
    </tbody></table></td>
            </tr>
        </tbody></table></td>
      </tr>
    </tbody></table></td>
    </tr>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= I18n.t('Title') %></title>
  <meta http-equiv="Content-Type" content="text/html; charset=gb2312">
  <meta name="Keywords" content="<%= I18n.t('Title') %>" />
  <meta name="Description" content="<%= I18n.t('Title') %>" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <style type="text/css">
  <!--
  .STYLE1 {color: #88AA0B}
  -->
  </style>
</head>

<body>
  <table width="970" border="0" align="center" cellpadding="0" cellspacing="0">
    <tr>
      <td height="102" align="right" valign="bottom" background="<%= image_url('top.jpg') %>" style="padding-bottom:22px;"><a href="#" onClick="this.style.behavior='url(#default#homepage)';this.setHomePage('http://www.shtableware.com');return false;" ><%= I18n.t('Homepage') %></a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;<a href="#" onClick="window.external.addFavorite('http://www.shtableware.com','<%= I18n.t('Title') %>');return false;" ><%= I18n.t('AddFavourite') %></a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;  <a href="<%= root_url(locale: @tab_locale) %>" class="STYLE1"><%= I18n.t('Language', locale: @tab_locale) %></a>&nbsp;&nbsp;</td>
    </tr>
    <tr>
      <td height="45" align="right" bgcolor="#250C10" style="padding-right:10px;"><table border="0" align="right" cellpadding="0" cellspacing="0">
        <tr>
          <td width="100" height="45" align="center" style="border-right:#7C6D70 1px solid"><a href="<%= root_url %>" class="t"><%= I18n.t('Home') %></a></td>
      <td width="100" height="45" align="center" style="border-right:#7C6D70 1px solid"><a href="<%= about_url %>" class="t"><%= I18n.t('AboutUs') %></a></td>
      <td width="100" height="45" align="center" style="border-right:#7C6D70 1px solid"><a href="#" class="t"><%= I18n.t('NewProducts') %></a></td>
      <td width="100" height="45" align="center" style="border-right:#7C6D70 1px solid"><a href="#" class="t"><%= I18n.t('Products') %></a></td>
      <td width="100" height="45" align="center" style="border-right:#7C6D70 1px solid"><a href="<%= network_url %>" class="t"><%= I18n.t('Network') %></a></td>
      <td width="100" height="45" align="center" style="border-right:#7C6D70 1px solid"><a href="<%= feedback_url %>" class="t"><%= I18n.t('Feedback') %></a></td>
      <td width="100" height="45" align="center"><a href="<%= contact_url %>" class="t"><%= I18n.t('ContactUs') %></a></td>
        </tr>
      </table></td>
    </tr>
  </table>
  <table width="1003" border="0" align="center" cellpadding="0" cellspacing="0" style="margin-top:17px;">
    <tr>
      <td align="center"><script>
    var NowFrame = 1;
    var MaxFrame = 3;
    var bStart = 0;
    function fnToggle() {
    var next = NowFrame + 1;
    if(next == MaxFrame+1) 
    {
    NowFrame = MaxFrame;
    next = 1;
    }
    if(bStart == 0)
    {
    bStart = 1;
          
    setTimeout('fnToggle()', 1000);
    return;
    }
    else
    {
    oTransContainer.filters[0].Apply();
    document.images['oDIV'+next].style.display = "";
    document.images['oDIV'+NowFrame].style.display = "none"; 
    oTransContainer.filters[0].Play(duration=5);
    if(NowFrame == MaxFrame) 
    NowFrame = 1;
    else
    NowFrame++;
    } setTimeout('fnToggle()', 6000);
    }
    fnToggle();
  </script>
          <!--焦点图片开始-->
          <div id="oTransContainer" style="FILTER: progid:DXImageTransform.Microsoft.Wipe(GradientSize=1.0, wipeStyle=0, motion='forward'); WIDTH: 970px; HEIGHT: 414px"><img src="<%= image_url('index_02.jpg')%>" name="oDIV1" width="970" height="414" border="0" id="oDIV1" style="BORDER-RIGHT: black 0px solid; BORDER-TOP: black 0px solid; DISPLAY: yes;  BORDER-LEFT: black 0px solid; BORDER-BOTTOM: black 0px solid" /><img id="oDIV2" style="BORDER-RIGHT: black 0px solid; BORDER-TOP: black 0px solid; DISPLAY: none; BORDER-LEFT: black 0px solid; BORDER-BOTTOM: black 0px solid" height="414" src="<%= image_url('index1_02.jpg')%>" width="970" border="0" /><img id="oDIV3" style="BORDER-RIGHT: black 0px solid; BORDER-TOP: black 0px solid; DISPLAY: none; BORDER-LEFT: black 0px solid; BORDER-BOTTOM: black 0px solid" height="414" src="<%= image_url('index2_02.jpg')%>" width="970" border="0" /></div>
      <!--焦点图片结束--></td>
    </tr>
  </table>
<%= yield %>
  <table width="970" border="0" align="center" cellpadding="0" cellspacing="0">
    <tr>
      <td><img src="<%= image_url('btmpic.jpg')%>" width="970" height="76"></td>
    </tr>
    <tr>
      <td height="65" align="center"><%= I18n.t('Copyright') %>：<%= I18n.t('Title') %><br>
      电话/TEL:xxxx-xxx-xxxxxxxx  传真/FAX：xxxx-xxx-xxxxxxxx  E-MAIL:<a href="mailto:xxxxxx@hotmail.com" target="_blank">xxxxxx@hotmail.com</a>,<a href="mailto:xxxxxx@xxxxxx.com" target="_blank">xxxxxx@xxxxxx.com</a></td>
    </tr> 
  </table>
</body>
</html>